apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-classifier-deployment
spec:
  replicas: 2 # Run 2 pods for availability
  selector:
    matchLabels:
      app: iris-classifier
  template:
    metadata:
      labels:
        app: iris-classifier
    spec:
      containers:
      - name: iris-api
        image: DOCKER_IMAGE_PLACEHOLDER # This will be replaced by our CI/CD pipeline
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /ready_check
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /live_check
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: "100m"      # Request 10% of a CPU core.
            memory: "128Mi"  # Request 128 Megabytes of RAM
          limits:
            cpu: "500m"      # Limit to 50% of a CPU core.
            memory: "512Mi"
